using HotelManagement.Application.Common;
using HotelManagement.Application.Domain.Entities;
using HotelManagement.Application.Features.Auth.Interfaces;
using HotelManagement.Application.Features.Room.Interfaces;
using MediatR;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Text;

namespace HotelManagement.Application.Features.Reservation.Commands
{
    public record CreateReservationCommand(
     int RoomId,
     string GuestName,
     DateOnly CheckInDate,
     DateOnly CheckOutDate
 ) : IRequest<int>;
   

    public class CreateReservationCommandHandler
        : IRequestHandler<CreateReservationCommand, int>
    {
        private readonly IAppDbContext _context;
        private readonly ICurrentUser _currentUserService;
        private readonly IHotelHubContext _hubContext;
        public CreateReservationCommandHandler(
            IAppDbContext context,
            ICurrentUser currentUserService,
             IHotelHubContext hubContext)

        {
            _context = context;
            _currentUserService = currentUserService;
            _hubContext = hubContext;
        }

        public async Task<int> Handle(
            CreateReservationCommand request,
            CancellationToken cancellationToken)
        {
            await using var transaction =
                await _context.Database.BeginTransactionAsync(
                    cancellationToken);

            try
            {
                // 1. Load Room
                var room = await _context.Rooms
                    .FirstOrDefaultAsync(
                        r => r.Id == request.RoomId,
                        cancellationToken);

                if (room is null)
                {
                    throw new KeyNotFoundException(
                        "Room not found.");
                }

                // 2. Validate dates
                if (request.CheckOutDate <= request.CheckInDate)
                {
                    throw new ArgumentException(
                        "Check-out date must be after check-in date.");
                }

                if (string.IsNullOrWhiteSpace(request.GuestName))
                {
                    throw new ArgumentException(
                        "Guest name is required.");
                }

                // 3. Check overlapping reservations
                var hasOverlap = await _context.Reservations
                    .AnyAsync(r =>
                        r.RoomId == request.RoomId &&
                        r.Status != "Cancelled" &&

                        request.CheckInDate < r.CheckOutDate &&
                        request.CheckOutDate > r.CheckInDate,

                        cancellationToken);

                if (hasOverlap)
                {
                    throw new InvalidOperationException(
                        "The room is already reserved for the selected dates.");
                }

                // 4. Calculate nights
                var nights =
                    request.CheckOutDate.DayNumber -
                    request.CheckInDate.DayNumber;

                var totalAmount =
                    nights * room.PricePerNight;

                // 5. Create reservation
                var reservation = new Domain.Entities.Reservation
                {
                    RoomId = request.RoomId,
                    GuestName = request.GuestName.Trim(),

                    CheckInDate = request.CheckInDate,
                    CheckOutDate = request.CheckOutDate,

                    TotalPrice = totalAmount,

                    Status = "Confirmed",

                    CreatedBy = _currentUserService.UserId,
                    CreatedAt = DateTime.UtcNow
                };

                _context.Reservations.Add(reservation);
                await _context.SaveChangesAsync(cancellationToken);


                // 6. Update IsAvailable
                room.IsAvailable = false;

                // 7. Create Audit Log
                var auditLog = new AuditLog
                {
                    Action = "CreateReservation",
                    EntityName = nameof(Reservation),

                    // IMPORTANT:
                    // reservation.Id is generated by EF/database.
                    EntityId = reservation.Id.ToString(),

                    UserId = _currentUserService.UserId,

                    ActionDate = DateTime.UtcNow,

                    Details =
                        $"Reservation created for room {room.RoomNumber}, " +
                        $"guest {reservation.GuestName}, " +
                        $"from {reservation.CheckInDate} " +
                        $"to {reservation.CheckOutDate}."
                };

                _context.AuditLogs.Add(auditLog);

                await _context.SaveChangesAsync(cancellationToken);

                await _hubContext.SendReservationCreatedAsync(
             
               new
                {
                 reservation.Id,
                 reservation.Room.RoomNumber,
                 reservation.GuestName,
                 reservation.CheckInDate,
                 reservation.CheckOutDate,
                 reservation.Status
                 },
               cancellationToken
);


                await transaction.CommitAsync(cancellationToken);

               

                return reservation.Id;
            }
            catch
            {
                await transaction.RollbackAsync(cancellationToken);
                throw;
            }
        }
    }

}
